### ISSUE TITLE
Add units to FrosstAlkEthOH on topology branch

### ISSUE THREAD

**Issue by proteneer** [openforcefield/openforcefield#186]
```
Error encountered parsing XMLline 49:
<Element Atom at 0x7fee21e3a488>

Traceback (most recent call last):
  File "examples/label_molecule/label_molecule.py", line 16, in <module>
    ff = ForceField('Frosst_AlkEthOH.offxml')
  File "/home/yutong/Code/timemachine/openforcefield/openforcefield/typing/engines/smirnoff/forcefield.py", line 232, in __init__
    self.parse(sources)
  File "/home/yutong/Code/timemachine/openforcefield/openforcefield/typing/engines/smirnoff/forcefield.py", line 603, in parse
    parameter_io_handler.parse_file(source)
  File "/home/yutong/Code/timemachine/openforcefield/openforcefield/typing/engines/smirnoff/io.py", line 311, in parse_file
    self.from_lxml(tree.getroot())
  File "/home/yutong/Code/timemachine/openforcefield/openforcefield/typing/engines/smirnoff/io.py", line 444, in from_lxml
    raise e
  File "/home/yutong/Code/timemachine/openforcefield/openforcefield/typing/engines/smirnoff/io.py", line 435, in from_lxml
    handler.add_parameter(parameter_kwargs)
  File "/home/yutong/Code/timemachine/openforcefield/openforcefield/typing/engines/smirnoff/parameters.py", line 301, in add_parameter
    self.check_parameter_compatibility(parameter_kwargs)
  File "/home/yutong/Code/timemachine/openforcefield/openforcefield/typing/engines/smirnoff/parameters.py", line 265, in check_parameter_compatibility
    if not (reqd_unit.is_compatible(val.unit)):
AttributeError: 'str' object has no attribute 'unit'
```

the label_molecule.py code is currently broken again. It looks like the r_min in VdW's in Frosst_AlkEthOH files are missing units:
``` xml
<vdW potential="Lennard-Jones-12-6" combining_rules="Loentz-Berthelot" scale12="0.0" scale13="0.0" scale14="0.5" scale15="1" sigma_unit="angstroms" epsilon_unit="kilocalories_per_mole" switch="8.0*angstroms" cutoff="9.0*angstroms" long_range_dispersion="isotropic">
   <!-- sigma is in angstroms, epsilon is in kcal/mol -->
   <Atom smirks="[#1:1]" rmin_half="1.4870" epsilon="0.0157" id="n0001" parent_id="n0001"/> <!-- making HC the generic hydrogen -->
   <Atom smirks="[$([#1]-[#6]):1]" rmin_half="1.4870" epsilon="0.0157" id="n0002" parent_id="n0001"/> <!-- HC from frcmod.Frosst_AlkEthOH -->
   <Atom smirks="[$([#1]-[#6]-[#7,#8,#9,#16,#17,#35]):1]" rmin_half="1.3870" epsilon="0.0157" id="n0003" parent_id="n0002"/> <!-- H1 from frcmod.Frosst_AlkEthOH -->
   <Atom smirks="[$([#1]-[#6](-[#7,#8,#9,#16,#17,#35])-[#7,#8,#9,#16,#17,#35]):1]" rmin_half="1.2870" epsilon="0.0157" id="n0004" parent_id="n0003"/> <!--H2 from frcmod.Frosst_AlkEthOH -->
   <Atom smirks="[$([#1]-[#6](-[#7,#8,#9,#16,#17,#35])(-[#7,#8,#9,#16,#17,#35])-[#7,#8,#9,#16,#17,#35]):1]" rmin_half="1.1870" epsilon="0.0157" id="n0005" parent_id="n0004"/> <!--H3 from frcmod.Frosst_AlkEthOH -->
   <Atom smirks="[#1$(*-[#8]):1]" rmin_half="0.0000" epsilon="0.0000" id="n0006" parent_id="n0001"/> <!-- HO from frcmod.Frosst_AlkEthOH -->
   <Atom smirks="[#6:1]" rmin_half="1.9080" epsilon="0.1094" id="n0007" parent_id="n0007"/> <!-- making CT the generic carbon -->
   <Atom smirks="[#6X4:1]" rmin_half="1.9080" epsilon="0.1094" id="n0008" parent_id="n0007"/> <!-- CT from frcmod.Frosst_AlkEthOH-->
   <Atom smirks="[#8:1]" rmin_half="1.6837" epsilon="0.1700" id="n0009" parent_id="n0009"/> <!-- making OS the generic oxygen -->
   <Atom smirks="[#8X2:1]" rmin_half="1.6837" epsilon="0.1700" id="n0010" parent_id="n0009"/> <!-- OS from frcmod.Frosst_AlkEthOH -->
   <Atom smirks="[#8X2+0$(*-[#1]):1]" rmin_half="1.7210" epsilon="0.2104" id="n0011" parent_id="n0009"/> <!-- OH from frcmod.Frosst_AlkEthOH -->
</vdW>
```

**Comment by jchodera** [comment]
It's likely we still have to update `Frosst_AlkEthOH.offxml` to the latest [SMIRNOFF spec](https://open-forcefield-toolkit.readthedocs.io/en/topology/smirnoff.html) with the latest unit-handling modifications.

**Comment by proteneer** [comment]
Thanks @andrrizzi - closing this.
