### ISSUE TITLE
Unable to create custom topology for phosphated ligand molecule due to unspecified chirality.

### ISSUE THREAD

**Issue by yabmtm** [openforcefield/openforcefield#545]
It appears that overriding antechamber command with -nc -1 allows the script to run without error, but this is not automatically detected, so trying to run the script returns:

```
Traceback (most recent call last):
  File "simulate.py", line 37, in <module>
    ligand = Molecule.from_file(ligand_file)
  File "/home/tug27224/packages/miniconda3/envs/work/lib/python3.7/site-packages/openforcefield/topology/molecule.py", line 2991, in from_file
    allow_undefined_stereo=allow_undefined_stereo)
  File "/home/tug27224/packages/miniconda3/envs/work/lib/python3.7/site-packages/openforcefield/utils/toolkits.py", line 1558, in from_file
    mol = self.from_rdkit(rdmol, allow_undefined_stereo=allow_undefined_stereo)
  File "/home/tug27224/packages/miniconda3/envs/work/lib/python3.7/site-packages/openforcefield/utils/toolkits.py", line 1879, in from_rdkit
    err_msg_prefix="Unable to make OFFMol from RDMol: ")
  File "/home/tug27224/packages/miniconda3/envs/work/lib/python3.7/site-packages/openforcefield/utils/toolkits.py", line 2427, in _detect_undefined_stereo
    raise UndefinedStereochemistryError(msg)
openforcefield.utils.toolkits.UndefinedStereochemistryError: Unable to make OFFMol from RDMol: Unable to make OFFMol from RDMol: RDMol has unspecified stereochemistry. RDMol name: O=C(NC[PH](=O)O)OCc1ccccc1Undefined chiral centers are:
 - Atom P (index 4)
```

**Comment by yabmtm** [comment]
[bad_ligand.zip](https://github.com/openforcefield/openforcefield/files/4340337/bad_ligand.zip)

**Comment by jchodera** [comment]
The error says the molecule has unspecified stereochemistry at atom `P`:
```
openforcefield.utils.toolkits.UndefinedStereochemistryError: Unable to make OFFMol from RDMol: Unable to make OFFMol from RDMol: RDMol has unspecified stereochemistry. RDMol name: O=C(NC[PH](=O)O)OCc1ccccc1
Undefined chiral centers are:
 - Atom P (index 4)
```
While the phosphate looks pretty suspect, the issue is that (1) this is a 2D SDF file from which the stereochemistry of that chiral center cannot be determined. If you provide an SDF file with 3D coordinates, it should work. Please reopen if you run into more issues!
