### ISSUE TITLE
Unsure how to import small molecule

### ISSUE THREAD

**Issue by corinwagen** [openforcefield/openforcefield#611]
**Describe the bug**
I'm trying to follow the steps at [this link](https://github.com/openforcefield/openforcefield/blob/master/examples/SMIRNOFF_simulation/run_simulation.ipynb) to use OpenFF/OpenMM to run MD on small molecules, but I haven't been able to load in any structures. I have the 3D coordinates of my molecule (testing on propylene but hoping to extend to other cases where SMILES/name import might not work) but I can't find a way to import it! I've tried the below `.sdf` solution as well as `.mol` and `.mol2` files, but can't seem to load the information in an `openforcefield`-compatible way. It's possible that GaussView is creating files that are missing some information?

I would appreciate guidance on how to go from an `.xyz` file or equivalent to an `openforcefield` `Molecule` instance. 

**To Reproduce**
Here's my code:

```
from openforcefield.topology import Molecule, Topology
from openforcefield.typing.engines.smirnoff import ForceField

from simtk import openmm, unit

pdbfile = openmm.app.PDBFile('propylene.pdb')
mol = Molecule.from_file('propylene.sdf')
```

propylene.pdb: 
```
REMARK   1 File created by GaussView 6.0.16
HETATM    1  C           0      -1.459  -1.439   0.000                       C
HETATM    2  H           0      -1.101  -2.447  -0.001                       H
HETATM    3  H           0      -1.104  -0.933  -0.874                       H
HETATM    4  H           0      -2.529  -1.441   0.001                       H
HETATM    5  C           0      -0.946  -0.713   1.257                       C
HETATM    6  C           0      -1.234   0.554   1.522                       C
HETATM    7  H           0      -0.321  -1.330   1.918                       H
HETATM    8  H           0      -0.868   1.072   2.418                       H
HETATM    9  H           0      -1.859   1.170   0.861                       H
END
CONECT    1    2    3    4    5
CONECT    2    1
CONECT    3    1
CONECT    4    1
CONECT    5    6    7    1
CONECT    6    5    8    9
CONECT    7    5
CONECT    8    6
CONECT    9    6
```
propylene.sdf:
```
Molecule Name

Created by GaussView 6.0.16
  9  8  0  0  0  0  0  0  0  0  0    0
   -1.4590   -1.4390    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1010   -2.4470   -0.0010 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1040   -0.9330   -0.8740 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.5290   -1.4410    0.0010 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9460   -0.7130    1.2570 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2340    0.5540    1.5220 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3210   -1.3300    1.9180 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8680    1.0720    2.4180 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.8590    1.1700    0.8610 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  1  3  1  0  0  0  0
  1  4  1  0  0  0  0
  1  5  1  0  0  0  0
  5  6  2  0  0  0  0
  5  7  1  0  0  0  0
  6  8  1  0  0  0  0
  6  9  1  0  0  0  0
M  END
```

**Output**

```
LICENSE: Could not open license file "oe_license.txt" in local directory
LICENSE: N.B. OE_LICENSE environment variable is not set
LICENSE: N.B. OE_DIR environment variable is not set
LICENSE: No product keys!
LICENSE: No product keys!
LICENSE: No product keys!
LICENSE: No product keys!
Warning: Unable to load toolkit 'OpenEye Toolkit'. The Open Force Field Toolkit does not require the OpenEye Toolkits, and can use RDKit/AmberTools instead. However, if you have a valid license for the OpenEye Toolkits, consider installing them for faster performance and additional file format support: https://docs.eyesopen.com/toolkits/python/quickstart-python/linuxosx.html OpenEye offers free Toolkit licenses for academics: https://www.eyesopen.com/academic-licensing
/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/simtk/openmm/app/internal/pdbstructure.py:537: UserWarning: WARNING: duplicate atom (HETATM    3  H           0      -1.104  -0.933  -0.874  1.00  0.00           H  , HETATM    2  H           0      -1.101  -2.447  -0.001  1.00  0.00           H  )
  warnings.warn("WARNING: duplicate atom (%s, %s)" % (atom, old_atom._pdb_string(old_atom.serial_number, atom.alternate_location_indicator)))
/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/simtk/openmm/app/internal/pdbstructure.py:537: UserWarning: WARNING: duplicate atom (HETATM    4  H           0      -2.529  -1.441   0.001  1.00  0.00           H  , HETATM    3  H           0      -1.104  -0.933  -0.874  1.00  0.00           H  )
  warnings.warn("WARNING: duplicate atom (%s, %s)" % (atom, old_atom._pdb_string(old_atom.serial_number, atom.alternate_location_indicator)))
/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/simtk/openmm/app/internal/pdbstructure.py:537: UserWarning: WARNING: duplicate atom (HETATM    5  C           0      -0.946  -0.713   1.257  1.00  0.00           C  , HETATM    1  C           0      -1.459  -1.439   0.000  1.00  0.00           C  )
  warnings.warn("WARNING: duplicate atom (%s, %s)" % (atom, old_atom._pdb_string(old_atom.serial_number, atom.alternate_location_indicator)))
/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/simtk/openmm/app/internal/pdbstructure.py:537: UserWarning: WARNING: duplicate atom (HETATM    6  C           0      -1.234   0.554   1.522  1.00  0.00           C  , HETATM    5  C           0      -0.946  -0.713   1.257  1.00  0.00           C  )
  warnings.warn("WARNING: duplicate atom (%s, %s)" % (atom, old_atom._pdb_string(old_atom.serial_number, atom.alternate_location_indicator)))
/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/simtk/openmm/app/internal/pdbstructure.py:537: UserWarning: WARNING: duplicate atom (HETATM    7  H           0      -0.321  -1.330   1.918  1.00  0.00           H  , HETATM    4  H           0      -2.529  -1.441   0.001  1.00  0.00           H  )
  warnings.warn("WARNING: duplicate atom (%s, %s)" % (atom, old_atom._pdb_string(old_atom.serial_number, atom.alternate_location_indicator)))
/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/simtk/openmm/app/internal/pdbstructure.py:537: UserWarning: WARNING: duplicate atom (HETATM    8  H           0      -0.868   1.072   2.418  1.00  0.00           H  , HETATM    7  H           0      -0.321  -1.330   1.918  1.00  0.00           H  )
  warnings.warn("WARNING: duplicate atom (%s, %s)" % (atom, old_atom._pdb_string(old_atom.serial_number, atom.alternate_location_indicator)))
/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/simtk/openmm/app/internal/pdbstructure.py:537: UserWarning: WARNING: duplicate atom (HETATM    9  H           0      -1.859   1.170   0.861  1.00  0.00           H  , HETATM    8  H           0      -0.868   1.072   2.418  1.00  0.00           H  )
  warnings.warn("WARNING: duplicate atom (%s, %s)" % (atom, old_atom._pdb_string(old_atom.serial_number, atom.alternate_location_indicator)))
[13:24:41] ERROR: CTAB version string invalid at line 4
[13:24:41] ERROR: moving to the beginning of the next molecule
Traceback (most recent call last):
  File "test_openff.py", line 9, in <module>
    mol = Molecule.from_file('propylene.sdf')
  File "/n/home03/cwagen/.conda/envs/openmm/lib/python3.7/site-packages/openforcefield/topology/molecule.py", line 3001, in from_file
    'Unable to read molecule from file: {}'.format(file_path))
Exception: Unable to read molecule from file: propylene.sdf
```

**Computing environment (please complete the following information):**
Python 3.7.6, AmberTools 19, openforcefield 0.6.0, openmm 7.4.2, rdkit 2020.03.2, Anaconda 5.0.1

**Additional context**
Thanks for the help!

**Comment by davidlmobley** [comment]
It looks to me like RDKit's SDF reader is choking on your input sdf file (you're using the RDKit backend since you're not using OpenEye). I'd guess, given the error message about "CTAB version string invalid at line 4", it's having a problem with the 4th line of your file, which says "Created by GaussView 6.0.16". Maybe it is unhappy with spaces, which I THINK may not be typical for these.

I generated a quick propylene sdf file myself using the OpenEye toolkits and it looks something like this. Perhaps you'd care to try this in your setup and see if it'd run. It may just be something silly like needing to remove the spaces or decimals or both from that GaussView line noted above.

```

  -OEChem-06012008573D

  9  8  0     0  0  0  0  0  0999 V2000
    0.8212   -0.6789   -0.2025 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.3491   -1.4450    0.7582 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8797   -1.4501    2.1744 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2086   -0.7222   -1.2145 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    2.1710   -2.1092    0.5059 H   0  0  0  0  0  0  0  0  0  0  0  0
    1.4342   -0.7057    2.7538 H   0  0  0  0  0  0  0  0  0  0  0  0
    1.0159   -2.4253    2.6524 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1838   -1.1958    2.2155 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0  0  0  0
  2  3  1  0  0  0  0
  1  4  1  0  0  0  0
  1  5  1  0  0  0  0
  2  6  1  0  0  0  0
  3  7  1  0  0  0  0
  3  8  1  0  0  0  0
  3  9  1  0  0  0  0
M  END
$$$$
```

**Comment by davidlmobley** [comment]
(I'm not currently running the RDKit backend or I'd try it myself; I can dig in if this doesn't get you anywehre, but it would take longer because I'd have to make a new conda env, etc.)

**Comment by j-wags** [comment]
I'm not used to seeing so many columns in the bonds section. I know that there's a difference between V2000 and V3000 mol/sdf files, but none of the documentation for those covers the extra columns. Is there a spec for the subtype of SDF files that Gaussian will write out? It would be good to add logic to handle that if there's another format we should check for.

I can get it to work if I replace the last three `0`s on the counts line with `0999 V2000`. This still doesn't help with the root cause, though. 

```
Molecule Name

Created by GaussView 6.0.16
  9  8  0  0  0  0  0  0  0  0999 V2000
   -1.4590   -1.4390    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1010   -2.4470   -0.0010 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1040   -0.9330   -0.8740 H   0  0  0  0  0  0  0  0  0  0  0  0
   -2.5290   -1.4410    0.0010 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9460   -0.7130    1.2570 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2340    0.5540    1.5220 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3210   -1.3300    1.9180 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8680    1.0720    2.4180 H   0  0  0  0  0  0  0  0  0  0  0  0
   -1.8590    1.1700    0.8610 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  1  3  1  0  0  0  0
  1  4  1  0  0  0  0
  1  5  1  0  0  0  0
  5  6  2  0  0  0  0
  5  7  1  0  0  0  0
  6  8  1  0  0  0  0
  6  9  1  0  0  0  0
M  END
```
