### ISSUE TITLE
Pytest fails locally with `--runslow already added`

### ISSUE THREAD

**Issue by trevorgokey** [openforcefield/openforcefield#708]
**Describe the bug**
Trying to run tests locally via `pytest` fails due to `--runslow already added`. It appears other plugins can define the same option, and in my case this seems to be qcfractal.

**To Reproduce**
Install qcfractal
Run tests

**Output**
The full error message (may be large, that's fine. Better to paste too much than too little.)
```Traceback (most recent call last):
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/_pytest/config/__init__.py", line 440, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/home/tgokey/projects/openforcefield/openforcefield/tests/conftest.py')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tgokey/.local/miniconda3/envs/oFF/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/_pytest/config/__init__.py", line 63, in main
    config = _prepareconfig(args, plugins)
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/_pytest/config/__init__.py", line 207, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/_pytest/helpconfig.py", line 94, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/_pytest/config/__init__.py", line 687, in pytest_cmdline_parse
    self.parse(args)
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/_pytest/config/__init__.py", line 895, in parse
    self._preparse(args, addopts=addopts)
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/_pytest/config/__init__.py", line 851, in _preparse
    early_config=self, args=args, parser=self._parser
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/_pytest/config/__init__.py", line 750, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(early_config.known_args_namespace)
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/_pytest/config/__init__.py", line 386, in _set_initial_conftests
    self._try_load_conftest(current)
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/_pytest/config/__init__.py", line 394, in _try_load_conftest
    self._getconftestmodules(x)
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/_pytest/config/__init__.py", line 424, in _getconftestmodules
    mod = self._importconftest(conftestpath.realpath())
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/_pytest/config/__init__.py", line 474, in _importconftest
    self.consider_conftest(mod)
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/_pytest/config/__init__.py", line 527, in consider_conftest
    self.register(conftestmodule, name=conftestmodule.__file__)
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/_pytest/config/__init__.py", line 321, in register
    ret = super(PytestPluginManager, self).register(plugin, name)
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/pluggy/manager.py", line 127, in register
    hook._maybe_apply_history(hookimpl)
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/pluggy/hooks.py", line 333, in _maybe_apply_history
    res = self._hookexec(self, [method], kwargs)
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/tgokey/projects/openforcefield/openforcefield/tests/conftest.py", line 73, in pytest_addoption
    "--runslow", action="store_true", default=False, help="run slow tests"
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/_pytest/config/argparsing.py", line 73, in addoption
    self._anonymous.addoption(*opts, **attrs)
  File "/home/tgokey/.local/miniconda3/envs/oFF/lib/python3.7/site-packages/_pytest/config/argparsing.py", line 304, in addoption
    raise ValueError("option names %s already added" % conflict)
ValueError: option names {'--runslow'} already added
```

**Additional context**
Here is the header when the testing proceeds:
```
(oFF) Sat 10:08 697: ~/projects/openforcefield/openforcefield ✔master» pytest
=============================================================================================== test session starts ================================================================================================
platform linux -- Python 3.7.8, pytest-4.6.4, py-1.9.0, pluggy-0.13.1
rootdir: /home/tgokey/projects/openforcefield
plugins: forked-1.2.0, xdist-1.33.0, qcfractal-0.13.1
```

**Comment by mattwthompson** [comment]
Related https://github.com/MolSSI/QCFractal/issues/585 (good to have it on our tracker, though)

**Comment by trevorgokey** [comment]
Yes, I see, thanks for pointing that issue out. We should try to resolve this ASAP with something that allows local testing with an environment with both packages present. I offered a PR, but if we are more inclined with another pathway then I am all for it.

**Comment by mattwthompson** [comment]
I'd also like to enable the  `--runslow` behavior to the nightly cron jobs. I don't know if those test have been run lately, and I certainly don't have the patience to do that locally. It doesn't need to be implemented as part of the solution here, just made possible.

**Comment by trevorgokey** [comment]
As a follow up, this `pytest` command will prevent plugins from being loaded, and explicitly loads the `xdist` plugin `conda install pytest-xdist` to run tests in parallel:
```
PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 pytest -p xdist -n 16
```
This will avoid loading unused plugins which may pollute the argument namespace.
